### ISSUE TITLE
Desktop Integration

### ISSUE THREAD

**Issue by rvasilev** [arch-noob/filebot#3]
- [x] use upstream .desktop files
 - [ ] install MIME for license file import
 - [ ] install file-manager actions?
 - [x] install icon to the standard location?

**Comment by KucharczykL** [comment]
Hi, this is an old issue but I suppose it would belong here. The icon is not displaying in KDE for me and as far as I can tell it's because instead of being in `/usr/share/icons/hicolor/scalable/apps` it's in `/usr/share/icons/scalable/apps` (ie. missing `hicolor`). Curiously, the icon is correctly placed in the tar.xz archive downloaded from Filebot so I assume the mistake happens during the package building and installation on Arch.

**Comment by rvasilev** [comment]
@KucharczykL 

icon placement shold be fixed

https://github.com/arch-noob/filebot/commit/ca406830eb7361163c350de67d0e113ac55083c1
